### ISSUE TITLE
Pypiserver Labels for deployment and pods

### ISSUE THREAD

**Issue by fr-ser** [owkin/charts#6]
In our stack we use labels to identify pods to make the logs command more easily repeatable.

How about I add this option to the config (you already have the same for service and ingress).

I would say the key would be deployment.labels (like services for example) and they would also be applied to pods.

**Comment by ClementGautier** [comment]
Hey there,

You are on :fire:!

It would definitely make sense. I fixed the CI so it should be faster for me to merge stuffs, go ahead with this and I´ll review that asap.

**Comment by fr-ser** [comment]
Cool, will do this within the next days! (All the changes suggested are just stuff we had to do at my company to get the pypiserver to our needs)
At the end we will probably use your chart unchanged :laughing:
