### ISSUE TITLE
Ability to specifiy arguments for pypiserver

### ISSUE THREAD

**Issue by fr-ser** [owkin/charts#7]
I would like to specify the --disable-fallback as an argument to the pypiserver, but there is currently no option for that.

How about we add a pypiserver.commandOptions (list) option for values.

The only problem I see is possible duplicates (you already specify the -P, -p and -a flag...

Optimal would be an overwrite possibility, but I will have to check that out.

Is this in line with your ideas?

**Comment by ClementGautier** [comment]
:wave: 

I see. The most flexible and common implementation I see is to pass "extra args", something like that:
```
command: ["pypi-server"]
args:
  - --passwords=/config/.htpasswd
  - --authenticate={{ .Values.auth.actions }}
  - --port=8080
  {{- range $key, $value := .Values.extraArgs }}
    {{- if $value }}
  - --{{ $key }}={{ $value }}
    {{- else }}
  - --{{ $key }}
    {{- end }}
  {{- end }}
  - /data/packages
```

To be tested tho.
 I'd gladly merge that ;)
