### ISSUE TITLE
Persistent Volume Claim Security Context

### ISSUE THREAD

**Issue by mkolb-navican** [owkin/charts#9]
In the pypiserver helm chart you need to add a fsGroup security context to the template spec so that the persistent volume claim, /data/packages, mount path group ownership is the pypiserver group (see the pypiserver docker hub dockerfile for the user and group guids). Otherwise, you will not have permissions to add files to the packages directory.

securityContext:
        fsGroup: 9898

Also, their pypiserver dockerfile has an error which they haven't fixed yet. The py2-pip package needs to be in the base image otherwise the 'pypi-server -U' command does not work.

And, just a side note i don't think that you need the following code in the deployment resource:

{{- else }}
          emptyDir: {}

The mountPath is dependent on the persistent volume, So, if you set up {{- if Values.persistence.enable }} logic around the Volumes: and volumeMounts: you don't need the {{- else }}

Checkout the AWS integration for ELB, NLB, and ALB. The service resource can be annotated to create the desired resource which negates the need for an ingress resource. 

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

https://hub.docker.com/r/pypiserver/pypiserver/dockerfile
https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

**Comment by ClementGautier** [comment]
Hi !

Sorry for the delay and thank you for the details. 
We indeed merged some pull requests in that regard recently that fixes your concern.
Security context is now configurable using the values here: https://github.com/owkin/charts/blob/11663b39d2e095d8f87301e4ed840d41e1131757/pypiserver/values.yaml#L75-L79
